language: cpp
compiler: gcc
script:
  - sh -x bootstrap.sh
  - env CFLAGS="-Wall -Wextra" CPPFLAGS="-Wall -Wextra" ./configure --disable-systemd
  - make
  - sh tools/test.sh
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libev-dev
    - libusb-1.0-0-dev
